name: CI/CD Sentiment Analysis API

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual triggering from GitHub UI
  schedule:           # optional, cron style for periodic retraining
    - cron: '0 0 * * 0'  # every Sunday at midnight

jobs:
  build-and-test:
    name: Build, Install, Train, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Dry-run model training
        run: python train_and_evaluate.py

      - name: Run unit tests
        run: |
          if [ -d "tests" ]; then
            pytest tests/
          else
            echo "No tests directory found. Skipping tests."
          fi

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v3
        with:
          name: sentiment_model
          path: sentiment_model.pkl

  deploy:
    name: Deploy to Azure App Service
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download trained model artifact
        uses: actions/download-artifact@v3
        with:
          name: sentiment_model
          path: .

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: YourAppServiceName
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .
